#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [[ $1 =～ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
  ping -c 5 "$1"
else
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
